// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXcFb3sZxdmRKiibe0E4NDBdzs1XEPC5o',
    appId: '1:54151174664:web:f979f1299d67c4cb9b0fbd',
    messagingSenderId: '54151174664',
    projectId: 'final-app-2567',
    authDomain: 'final-app-2567.firebaseapp.com',
    storageBucket: 'final-app-2567.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAa6RRGK0MmOgg4VyBakD8DDFmqhInN9o',
    appId: '1:54151174664:android:591db72e86b0ea939b0fbd',
    messagingSenderId: '54151174664',
    projectId: 'final-app-2567',
    storageBucket: 'final-app-2567.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKCR6DZJNuEUqFGFHYZUIR9AY-LezbfYo',
    appId: '1:54151174664:ios:47d2ebab7b8f68439b0fbd',
    messagingSenderId: '54151174664',
    projectId: 'final-app-2567',
    storageBucket: 'final-app-2567.firebasestorage.app',
    iosBundleId: 'com.example.finalApp',
  );
}
